#ifndef __SAVEFILES_H__
#define __SAVEFILES_H__

#define SAVE_NETWORK			0x01
#define SAVE_TRAIN				0x02
#define SAVE_TEST				0x03

#define SAVE_NET_WEIGHTS		0x11
#define SAVE_NET_TARGETS		0x12

#define SAVE_TRAIN_DELTA_WMAGS	0x21
#define SAVE_TRAIN_ITER_COUNTS	0x22
#define SAVE_TRAIN_ENERGIES		0x23
#define SAVE_TRAIN_LENERGIES	0x24
#define SAVE_TRAIN_TRAINCOSTS	0x25

#define SAVE_TEST_LABELS		0x31
#define SAVE_TEST_PREDICTIONS	0x32
#define SAVE_TEST_OUTPUTS		0x33
#define SAVE_TEST_COSTS			0x34

#endif